### ISSUE TITLE
RC4 on Android 4.2.1

### ISSUE THREAD

**Issue by swheater** [SQLDroid/SQLDroid#11] opened 2013-01-22 17:06 UTC
I am trying to write a simple test App for Android 4.2.1, using SQLDroid 1.0.0.RC4, but I am unable to create a database, despite using the ADDITONAL_DATABASE_FLAGS of CREATE_IF_NECESSARY and OPEN_READWRITE.

Sqldroid(13874): new sqlite jdbc from url 'jdbc:sqldroid: /data/data/org.test.android/databases/TestTest.db', '{AdditionalDatabaseFlags=268435456}'
SQlDRoid(13874): opening database  /data/dataorg.test.android/databases/TestTest.db
SQLiteLog(13874): (14) cannot open file at line 30176 of [00bb9c9ce4]
SQLiteLog(13874): (14) os_unix.c:30176: (2) open(// /data/data/org.test.android/databases/TestTest.db) - 
SQLiteDatabase(13874): Failed to open database ' /data/data/org.test.android/databases/TestTest.db'.
SQLiteDatabase(13874): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

Does SQLDroid support Android 4.2.1?

Stuart

**Comment by jhannes** [comment] 2016-08-17 21:21
It seems like this is not a bug, just wrong path to the database.

However, there are lots of issues related to missing/unwritable directories. Perhaps it would be a good idea to handle this specifically? Either verify that the directory exists and is writable or try to create it. What do you think @donv?

**Comment by donv** [comment] 2016-08-17 21:53
Yes, handling this sounds like the right thing to do.  Creating the parent directory if missing, and checking write permissions should lead to fewer errors and better error messages.

Go ahead if you can.  Great work @jhannes !

**Comment by jhannes** [comment] 2016-08-19 21:53
Since this was mostly a support request, I suggest closing it in favor of #74

**Closed by jhannes** 2016-08-19 21:53 UTC
Labels: Bug
