### ISSUE TITLE
Connections are not closed properly if setAutoCommit(false) has been called.

### ISSUE THREAD

**Issue by erikjber** [SQLDroid/SQLDroid#68] opened 2016-06-23 11:12 UTC
Connections where AutoCommit has been set to false does not release the database properly when they are closed.

To reproduce:
```
            Class.forName("org.sqldroid.SQLDroidDriver").newInstance();  
            Connection c1 = DriverManager.getConnection("jdbc:sqlite:" + getFilesDir() + "/test.db","test","test");  
            c1.setAutoCommit(false);  
            c1.close();
            Connection c2 = DriverManager.getConnection("jdbc:sqlite:" + getFilesDir() + "/test.db","test","test");  
            c2.close();
```

This results in an exeption:
`android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
                                                                                at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
                                                                                at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:804)
                                                                                at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:490)
                                                                                at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:464)
                                                                                at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:363)
                                                                                at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:228)
                                                                                at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
                                                                                at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
                                                                                at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
                                                                                at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:891)
                                                                                at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:861)
                                                                                at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
                                                                                at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
                                                                                at org.sqldroid.SQLiteDatabase.<init>(SQLiteDatabase.java:89)
                                                                                at org.sqldroid.SQLDroidConnection.<init>(SQLDroidConnection.java:131)
                                                                                at org.sqldroid.SQLDroidDriver.connect(SQLDroidDriver.java:64)
                                                                                at java.sql.DriverManager.getConnection(DriverManager.java:179)`

This works fine:
```
            Class.forName("org.sqldroid.SQLDroidDriver").newInstance();    
            Connection c1 = DriverManager.getConnection("jdbc:sqlite:" + getFilesDir() + "/test.db","test","test");    
            //c1.setAutoCommit(false); commented out    
            c1.close();    
            Connection c2 = DriverManager.getConnection("jdbc:sqlite:" + getFilesDir() + "/test.db","test","test");   
            c2.close(); 
```

The workaround is to simply set the autocommit flag to true before closing the connection.

**Comment by SStorm** [comment] 2016-06-24 13:50
+1, worse than that, commit() actually opens up a new transaction, effectively never releasing the DB from the current thread. This makes it impossible to use the driver in a multi-threaded android app environment.
```    @Override
    public void commit() throws SQLException {
        if (autoCommit) {
            throw new SQLException("database in auto-commit mode");
        }
        sqlitedb.setTransactionSuccessful();
        Log.d("END TRANSACTION  (commit) " + Thread.currentThread().getId() + " \"" + Thread.currentThread().getName() + "\" " + this);
        sqlitedb.endTransaction();
        Log.d("BEGIN TRANSACTION (after commit) " + Thread.currentThread().getId() + " \"" + Thread.currentThread().getName() + "\" " + this);
        sqlitedb.beginTransaction();
    }
```

**Comment by foreground-voice** [comment] 2016-06-29 11:56
why!!! It's so ugly on android. I have issue because of this: 
`W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/data/..../databases/....sqlite' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.`

There are few discussions about closing of database: http://stackoverflow.com/questions/14002022/android-sq-lite-closed-exception/25379071#25379071
http://stackoverflow.com/questions/6905524/using-singleton-design-pattern-for-sqlitedatabase/9286006#9286006. 
And if I have rightly understood that the [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html) have ability to autoclose database. But sqldroid don't using that class.
Simultaneously, Application don't have any destroy or termination event callback in which we would implement call db.close(). 
Please direct me if you get find solution for opened transaction problem.

**Comment by foreground-voice** [comment] 2016-08-08 05:05
@erikjber , do you have any solution of this issue at the moment?
I have found some information in wiki here:
https://github.com/SQLDroid/SQLDroid/wiki/Tips-and-tricks-%28including-database-locking%29
And there are another approaches such as:
"begin **immediate** transaction"
and 
ContentProvider - very drastically, I guess

**Closed** 2016-08-19 20:36 UTC
Labels: Bug

**Comment by aschmois** [comment] 2018-12-19 02:13
I have just confirmed (after very painful debugging) that auto commit to off is still a problem in 1.1.0-rc1
